# -*- coding: utf-8 -*-
"""Python_Data_Analysis_APIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17W45jOhDwa9BzEpPYcO8J26R2W6mbkYG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests

print("Libraries imported successfully!")

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 103],
    "Name": ["Akhila", "Anu", "Priya", "Rahul", "Sneha",
             "Kiran", "Divya", "Arjun", "Meena", "Ravi", "Priya"],
    "Department": ["CSE", "ECE", "CSE", "IT", "CSE",
                   "ECE", "IT", "CSE", "ECE", "IT", "CSE"],
    "Age": [21, 20, 21, 22, 20, 21, 22, 20, 21, 22, 21],
    "Marks": [85, 78, 92, 67, 88, np.nan, 76, 95, 81, 70, 92],
    "Attendance": [90, 85, 95, 75, 88, 80, np.nan, 96, 89, 72, 95]
}

df = pd.DataFrame(data)

# Save dataset
df.to_csv("student_performance.csv", index=False)

# Load dataset
df = pd.read_csv("student_performance.csv")

print("Dataset loaded successfully!")
display(df)

print("Missing values before cleaning:")
print(df.isnull().sum())

# Remove duplicate records
df = df.drop_duplicates()

# Fill missing Marks with average Marks
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# Fill missing Attendance with average Attendance
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())

print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nCleaned Dataset:")
display(df)

# Basic statistics
print("Average Marks:", round(df["Marks"].mean(), 2))
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())
print("Average Attendance:", round(df["Attendance"].mean(), 2))

# Department-wise average marks
department_average = df.groupby("Department")["Marks"].mean()

print("\nDepartment-wise Average Marks:")
print(department_average)

# Top student
top_student = df.loc[df["Marks"].idxmax()]

print("\nTop Performing Student:")
print("Name:", top_student["Name"])
print("Marks:", top_student["Marks"])

# Students who scored above 80
print("\nStudents scoring above 80:")
display(df[df["Marks"] > 80])

# Student Marks - Matplotlib
plt.figure(figsize=(10, 5))

plt.bar(df["Name"], df["Marks"])

plt.xlabel("Students")
plt.ylabel("Marks")
plt.title("Student Performance")

plt.xticks(rotation=45)
plt.show()


# Department-wise Marks - Seaborn
plt.figure(figsize=(8, 5))

sns.barplot(data=df, x="Department", y="Marks")

plt.title("Department-wise Average Performance")
plt.show()


# Marks Distribution
plt.figure(figsize=(8, 5))

sns.histplot(df["Marks"], kde=True)

plt.title("Distribution of Student Marks")
plt.xlabel("Marks")
plt.show()

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

print("HTTP Status Code:", response.status_code)

# Convert JSON response to Python data
api_data = response.json()

# Convert API data into DataFrame
api_df = pd.DataFrame(api_data)

print("\nAPI Data:")
display(api_df[["id", "name", "email"]])

total_students = len(df)
average_marks = df["Marks"].mean()
highest_marks = df["Marks"].max()
lowest_marks = df["Marks"].min()
average_attendance = df["Attendance"].mean()

report = f"""
========================================
     STUDENT PERFORMANCE REPORT
========================================

Total Students       : {total_students}
Average Marks        : {average_marks:.2f}
Highest Marks        : {highest_marks:.2f}
Lowest Marks         : {lowest_marks:.2f}
Average Attendance   : {average_attendance:.2f}

Department-wise Average Marks:
{department_average.to_string()}

Top Performing Student:
Name  : {top_student["Name"]}
Marks : {top_student["Marks"]}

========================================
"""

print(report)

df.to_csv("cleaned_student_performance.csv", index=False)

print("Cleaned dataset saved successfully!")
print("File name: cleaned_student_performance.csv")
